### PR TITLE
Remove focus from restart button

### PR DESCRIPTION
**Pull request by Banh983**
So i do a review on your code, interest game btw, so to fix your issue i set the restart button to blur, then just to make sure it wont focus on the restart button upon the next round i set the focus to somewhere else the the document body.
You right it just need 2 line of code:
image

### CODE REVIEW

**Comment by pandeyganesha** [comment]
@Banh983 Great !
But you seemed to have refactored the code.
Please make the changes needed to solve the issue only. Most changes seem to be changing single quotes into double quotes.

Please revert back refactoring changes. Also `restartButton.blur()` seems to be sufficient, we don't need `.focus` 

If you like to refactor the code and add documentation, you should create a new branch and raise separate PR.
Thanks, Will merge as soon as you fix this

**Comment by pandeyganesha** [comment]
@Banh983 
Dear this is not the way to revert. Git is still tracking all the changes.
The simple and easy way would be to discard all the changes in this. And then just add the `.blur()` line.
This is the clean and simple way. Git is showing changes in every line right now.

In other cases, you might want to revert back to previous commits. But since here is only one commit and you only need to add single line, discarding all the changes and adding the line is the clean way.

Please do that !

**Comment by Banh983** [comment]
Hi, sorry for the inconvenience, it happens because of the prettier setting on my computer, it made all the double quotes become single quotes, i restore the original state, can you check for merge please

**Comment by pandeyganesha** [comment]
@Banh983 I can still see those changes in this PR.
I actually fixed the things here https://github.com/pandeyganesha/digit-dare/commit/751c9d97fc235a16a015f2d97c47b2feb289122f
and was about merge changes but you `force-pushed` the changes.

image

You can yourself check the changes you have made by clicking on `files changed`

Please fix and review yourself either by using `git diff` or UI version of git diff before pushing any changes.
Thanks

**Comment by Banh983** [comment]
Oh i'm terribly sorry i using github desktop and it my first time solving a problem too, in the push that i made i did restore all of the single quote to double quote or any other changes, i made it look like in the original state, and i remove that .focus() line as you suggested

**Comment by pandeyganesha** [comment]
> Oh i'm terribly sorry i using github desktop and it my first time solving a problem too, in the push that i made i did restore all of the single quote to double quote or any other changes, i made it look like in the original state, and i remove that .focus() line as you suggested

No, it's fine. That's how we learn, we make mistakes, we learn from it. It's fine. Take your own time. Always review the changes before committing and pushing the changes.

**Comment by Banh983** [comment]
Thank you for your understanding, I really appreciate it, you can preview the code to see if it still have any problem I'm fixing it right away

**Comment by pandeyganesha** [comment]
Yes the refactored code is still there, also i can't see any new commit since my last reply.

**Comment by Banh983** [comment]
I'm sure that i did made those changes as you required and i did commit it right here
image

**Comment by Banh983** [comment]
Ohh i see the problem now, english actually not my mother tongue so i something have a different understanding in sentences,

**Comment by Banh983** [comment]
I think the code look okay, can you check for merger please 🤧🤧

**Comment by pandeyganesha** [comment]
Now It is fine. I can see that the refactored code has been removed. 
Thanks

Here are some tips that might help you in future.
1. Always give helpful commit message. Example: "Removed the refactored code and fixed the issue" is better than "Modify again"
2. Always review changes before committing.
3. and for making changes create new branches like `feature/<description-of-the-task>` or if you are fixing a bug then name it something like `bugfix/remove-focus-from-button`. And then make changes in that branch
4. Sync your code from the original repo before raising PR and then raise PR from the branch.

Nevertheless Thank you for your contribution. Merging and closing the PR.

**Pull request merged**
